#!/bin/sh
# Prove the launcher end to end, through the copy inside Project64.app, so the run also
# proves the emulator is found three directories up. A temporary folder holds two links to
# the ROM: nolayout.z64, which must start with the generic layout, and withlayout.z64, beside
# a layout with no menu, which must get one on mid5 (PJ64_MENU_AUTO). The launcher clicks
# each row in turn with synthetic events (--selftest), stops each game after
# PJ64_LAUNCHER_SELFTEST seconds, and must come back after each and list both as recent,
# newest first. Face is off and PJ64_FACE=0: the camera never opens.
# Design: Docs/superpowers/specs/2026-09-24-launcher-design.md
set -eu

ROM="${1:?usage: launcher_selftest.sh <rom>}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP_BIN="$ROOT/Bin/macOS/Project64.app/Contents/MacOS/Project64-launcher"

[ -x "$APP_BIN" ] || { echo "app not built: $APP_BIN (make all)" >&2; exit 1; }
[ -x "$ROOT/Bin/macOS/Project64" ] || { echo "frontend not built (make all)" >&2; exit 1; }
[ -f "$ROM" ] || { echo "no such ROM: $ROM" >&2; exit 1; }
case "$ROM" in /*) ;; *) ROM="$(pwd)/$ROM" ;; esac

WORK="$(mktemp -d /tmp/pj64-launcher-selftest-XXXXXX)"
trap 'rm -rf "$WORK"' EXIT
mkdir "$WORK/games" "$WORK/home"
ln -s "$ROM" "$WORK/games/nolayout.z64"
ln -s "$ROM" "$WORK/games/withlayout.z64"
cat > "$WORK/games/withlayout.yaml" <<'YAML'
bindings:
  Stick: {stick: pointer}
  A:     {zone: game}
YAML
cat > "$WORK/home/launcher.yaml" <<YAML
folder: "$WORK/games"
face: false
YAML

LOG="$WORK/log"
unset PJ64_INPUT_YAML PJ64_MENU_AUTO
if ! PJ64_FACE=0 PJ64_LAUNCHER_HOME="$WORK/home" PJ64_LAUNCHER_SELFTEST=6 \
    perl -e 'alarm 90; exec @ARGV' -- "$APP_BIN" --selftest >"$LOG" 2>&1; then
    cat "$LOG" >&2
    echo "launcher-selftest: the launcher did not finish cleanly" >&2
    exit 1
fi

fail() { cat "$LOG" >&2; echo "launcher-selftest: $1" >&2; exit 1; }
need() { grep -q -- "$1" "$LOG" || fail "missing: $1"; }
count() { N=$(grep -c -- "$1" "$LOG" || true); [ "$N" -eq "$2" ] || fail "wanted $2 of \"$1\", got $N"; }

need "^launcher: emulator $ROOT/Bin/macOS\$"
need "^launcher: started $WORK/games/nolayout.z64 with the generic layout\$"
need "^launcher: started $WORK/games/withlayout.z64\$"
need "^input layout: $WORK/games/withlayout.yaml\$"
count "^launcher: started " 2
count "^menu: added on mid5\$" 1
# SDL3 traps SIGTERM itself and turns it into a graceful SDL_EVENT_QUIT (SDL_events.h:
# "if the quit event is generated by a signal... it will be delivered to the application at
# the next event poll"), so the child's own event loop sees the quit and exits 0 through its
# normal cleanup path rather than dying by the raw signal; verified with a bare `./Project64`
# run outside the launcher too. "exit 0", not "signal 15", is what a clean stop looks like.
count "^launcher: game ended (exit 0)\$" 2
count "^launcher: window back\$" 2
need "^launcher: selftest ok\$"
echo "ok: launcher selftest"
