name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install pkg-config sdl3 yaml-cpp

      - name: Check dependencies
        run: make deps

      - name: Build
        run: make -j8 all

      - name: Smoke test
        run: make test

      - name: Unit tests
        run: make unit-test
